{% set version = "2.0.1" %}

package:
    name: pybind11
    version: {{ version }}

source:
    fn: pybind11-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pybind11/pybind11-{{ version }}.tar.gz
    sha256: 1b1a4824aad88b1073fe8dbd21683e1e5228f3ed3b29c2785fbf5dea6bf1063c

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pybind11

about:
    home: https://github.com/pybind/pybind11/
    license: BSD 3-Clause
    summary: Seamless operability between C++11 and Python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - wjakob
