{% set version = "3.0.0" %}
{% set sha256 = "453b1a3e2b266c3ae9da872411cadb6d693ac18063bd73226d96cfb7015a200c" %}

# this is set to PYBIND11_INTERNALS_VERSION
{% set abi_version = "4" %}

package:
  name: pybind11-split
  version: {{ version }}

source:
  fn: pybind11-{{ version }}.tar.gz
  url: https://github.com/pybind/pybind11/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    # ensure we make python a top level job
    - python {{ python_min }}

outputs:
  - name: pybind11-abi
    version: {{ abi_version }}
    build:
      noarch: generic
      run_exports:
        - pybind11-abi =={{ abi_version }}
      # This output is broken. Disabling for now
      # See https://github.com/conda-forge/pybind11-feedstock/issues/96
      skip: true
    test:
      source_files:
        - include/pybind11/detail/internals.h
      commands:
        # make sure the internals version matches the package version
        - if [ $(grep "#define PYBIND11_INTERNALS_VERSION" include/pybind11/detail/internals.h | cut -d' ' -f3) != "{{ abi_version }}" ]; then exit 1; fi  # [unix]

  - name: pybind11-global
    script: build-pybind11-global.sh  # [unix]
    script: build-pybind11-global.bat  # [win]
    build:
      noarch: python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cmake
        - make  # [unix]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        # layouts are different on unix vs win
        - __unix        # [unix]
        - __win         # [win]
      run_constrained:
        - pybind11-abi =={{ abi_version }}
    test:
      requires:
        - python {{ python_min }}
      commands:
        - echo "works!"

  - name: pybind11
    script: build-pybind11.sh  # [unix]
    script: build-pybind11.bat  # [win]
    build:
      noarch: python
      entry_points:
        - pybind11-config = pybind11.__main__:main
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cmake
        - make  # [unix]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - pybind11-global {{ PKG_VERSION }}=*_{{ PKG_BUILDNUM }}
      run_constrained:
        - pybind11-abi =={{ abi_version }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - pybind11
      commands:
        - test -f ${PREFIX}/share/cmake/pybind11/pybind11Config.cmake                                     # [unix]
        - if not exist %LIBRARY_PREFIX%\share\cmake\pybind11\pybind11Config.cmake exit 1      # [win]
        - test -f ${PREFIX}/include/pybind11/pybind11.h      # [unix]
        - if not exist %LIBRARY_INC%\pybind11\pybind11.h exit 1      # [win]
        - test -f $(python -c "import pybind11 as py; print(py.get_include())")/pybind11/pybind11.h      # [unix]
        - if not exist %SP_DIR%\pybind11\include\pybind11\pybind11.h exit 1      # [win]

about:
  home: https://github.com/pybind/pybind11/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Seamless operability between C++11 and Python
  doc_url: https://pybind11.readthedocs.io/

extra:
  feedstock-name: pybind11
  recipe-maintainers:
    - ax3l
    - SylvainCorlay
    - wjakob
    - henryiii
