{% set version = "2.4.3" %}
{% set sha256 = "1eed57bc6863190e35637290f97a20c81cfe4d9090ac0a24f3bbf08f265eb71d" %}

package:
    name: pybind11
    version: {{ version }}

source:
    fn: pybind11-{{ version }}.tar.gz
    url: https://github.com/pybind/pybind11/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - remconda.patch

build:
    number: 1

requirements:
    build:
        - cmake
        - make  # [unix]
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pybind11
    commands:
        - test -f ${PREFIX}/share/cmake/pybind11/pybind11Config.cmake                                 # [unix]
        - if exist %LIBRARY_PREFIX%\share\cmake\pybind11\pybind11Config.cmake (exit 0) else (exit 1)  # [win]
        - test -f $(python -c "import pybind11 as py; print(py.get_include())")/pybind11/pybind11.h   # [unix]
        - if exist $(python -c "import pybind11 as py; print(py.get_include())")\pybind11\pybind11.h (exit 0) else (exit 1)  # [win]

about:
    home: https://github.com/pybind/pybind11/
    license: BSD 3-Clause
    summary: Seamless operability between C++11 and Python
    license_file: LICENSE

extra:
  recipe-maintainers:
    - ax3l
    - SylvainCorlay
    - wjakob
