{% set version = "2.3.0" %}
{% set sha256 = "0f34838f2c8024a6765168227ba587b3687729ebf03dc912f88ff75c7aa9cfe8" %}

package:
    name: pybind11
    version: {{ version }}

source:
    fn: pybind11-{{ version }}.tar.gz
    url: https://github.com/pybind/pybind11/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1

requirements:
    build:
        - cmake
        - make  # [unix]
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pybind11
    commands:
        - test -f ${PREFIX}/share/cmake/pybind11/pybind11Config.cmake                         # [unix]
        - if exist %PREFIX%\share\cmake\pybind11\pybind11Config.cmake (exit 0) else (exit 1)  # [win]


about:
    home: https://github.com/pybind/pybind11/
    license: BSD 3-Clause
    summary: Seamless operability between C++11 and Python

extra:
  recipe-maintainers:
    - ax3l
    - SylvainCorlay
    - wjakob
