conda_build_tool: rattler-build
conda_install_tool: pixi
bot:
  automerge: false
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
conda_build:
  error_overlinking: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
noarch_platforms:
  - linux_64
  - win_64
